services:
  mcsm:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: mcsm
    ports:
      - 23333:23333
      - 24444:24444
      - 25565-25575:25565-25575
    volumes:
      - /data/mcsm/daemon/data:/opt/mcsm/daemon/data
      - /data/mcsm/web/data:/opt/mcsm/web/data
      - /data/mcsm/daemon/logs:/opt/mcsm/daemon/logs
      - /data/mcsm/web/logs:/opt/mcsm/web/logs